# Dependencies
gems: [jekyll-paginate, jekyll-gist]
markdown:         kramdown
highlighter:      pygments
paginate:         5


# Setup
site_name:            Gassa Yan
url:              http://www.gassayy.com
baseurl:          /


authors:
  gassa:
    name: Gassa Yan
    display_name: Gassa
    email: gassa0617@gmail.com
  bruce:
    name: Bruce Li
    display_name: Bruce
    email: leilmyxwz@gmail.com 


#Custom vars
version:          3.0.0

github:
  repo:           https://github.com/gassa
