# Author Information
authors:
  gassa:
    name: Gassa Yan
    display_name: Gassa
    email: gassa0617@gmail.com
  bruce:
    name: Bruce Li
    display_name: Bruce
    email: leilmyxwz@gmail.com

# Setup
site_name:  Gassa's Blog
url:        http://www.gassayy.com
baseurl:    /

# Markdown Rendering
kramdown: 
    parse_block_html: true

# Site settings
permalink: /blog/:year/:month/:day/:title/

# important since the site is compiled
# on Github's servers
timezone: America/New_York
